# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jan Wedekind
tagline:          'Computer Scientist (PhD)'
description:      'Computer scientist living in Eastleigh. Interested in machine vision, robotics, and software engineering. Also plays the harmonica.'
url:              http://www.wedesoft.de/
baseurl:          /

author:
  name:           'Jan Wedekind'
  url:            https://twitter.com/wedesoft

paginate:         3

# Custom vars
github:
  repo:           https://github.com/wedesoft/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
